services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: pari
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: